ALTER TABLE MES_ASSET ADD CONSTRAINT FK_ASSET_TYPE FOREIGN KEY  (mes_asset_type_code) REFERENCES MES_ASSET_TYPE (CODE);
ALTER TABLE MES_ASSET ADD CONSTRAINT FK_ASSET_GROUP FOREIGN KEY (mes_asset_group_code) REFERENCES MES_ASSET_GROUP (CODE);
ALTER TABLE MES_ASSET ADD CONSTRAINT KF_ASSET_STATUS FOREIGN KEY (mes_asset_status_code) references MES_ASSET_STATUS (CODE); 