server:
  port: 8090
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  servlet:
    contextPath: /openi40mes
  
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      serialization:
          INDENT_OUTPUT: true
com.openi40.mes.logical.kernel.config:
                                  apsMsgRestConfig: 
                                      url: http://localhost:8080/openi40      

  