export * from './oi40DbApsSchedulingSetRepository.service';
import { Oi40DbApsSchedulingSetRepositoryService } from './oi40DbApsSchedulingSetRepository.service';
export * from './oi40DbApsWindowRepository.service';
import { Oi40DbApsWindowRepositoryService } from './oi40DbApsWindowRepository.service';
export * from './oi40DbBomItemModelRepository.service';
import { Oi40DbBomItemModelRepositoryService } from './oi40DbBomItemModelRepository.service';
export * from './oi40DbChangeOverMatrixItemRepository.service';
import { Oi40DbChangeOverMatrixItemRepositoryService } from './oi40DbChangeOverMatrixItemRepository.service';
export * from './oi40DbCoProductItemRepository.service';
import { Oi40DbCoProductItemRepositoryService } from './oi40DbCoProductItemRepository.service';
export * from './oi40DbCycleModelRepository.service';
import { Oi40DbCycleModelRepositoryService } from './oi40DbCycleModelRepository.service';
export * from './oi40DbDepartmentRepository.service';
import { Oi40DbDepartmentRepositoryService } from './oi40DbDepartmentRepository.service';
export * from './oi40DbMachineEquipmentSpecificationRepository.service';
import { Oi40DbMachineEquipmentSpecificationRepositoryService } from './oi40DbMachineEquipmentSpecificationRepository.service';
export * from './oi40DbMachinePriorityRepository.service';
import { Oi40DbMachinePriorityRepositoryService } from './oi40DbMachinePriorityRepository.service';
export * from './oi40DbMachineRepository.service';
import { Oi40DbMachineRepositoryService } from './oi40DbMachineRepository.service';
export * from './oi40DbOperationEquipmentSpecificationRepository.service';
import { Oi40DbOperationEquipmentSpecificationRepositoryService } from './oi40DbOperationEquipmentSpecificationRepository.service';
export * from './oi40DbOperationModelRepository.service';
import { Oi40DbOperationModelRepositoryService } from './oi40DbOperationModelRepository.service';
export * from './oi40DbPartnerRepository.service';
import { Oi40DbPartnerRepositoryService } from './oi40DbPartnerRepository.service';
export * from './oi40DbPeggingRepository.service';
import { Oi40DbPeggingRepositoryService } from './oi40DbPeggingRepository.service';
export * from './oi40DbPlantProductSettingRepository.service';
import { Oi40DbPlantProductSettingRepositoryService } from './oi40DbPlantProductSettingRepository.service';
export * from './oi40DbPlantRepository.service';
import { Oi40DbPlantRepositoryService } from './oi40DbPlantRepository.service';
export * from './oi40DbProductRepository.service';
import { Oi40DbProductRepositoryService } from './oi40DbProductRepository.service';
export * from './oi40DbProductiveCompanyProductSettingRepository.service';
import { Oi40DbProductiveCompanyProductSettingRepositoryService } from './oi40DbProductiveCompanyProductSettingRepository.service';
export * from './oi40DbProductiveCompanyRepository.service';
import { Oi40DbProductiveCompanyRepositoryService } from './oi40DbProductiveCompanyRepository.service';
export * from './oi40DbPurchaseOrderLineRepository.service';
import { Oi40DbPurchaseOrderLineRepositoryService } from './oi40DbPurchaseOrderLineRepository.service';
export * from './oi40DbPurchaseOrderRepository.service';
import { Oi40DbPurchaseOrderRepositoryService } from './oi40DbPurchaseOrderRepository.service';
export * from './oi40DbResourceGroupRepository.service';
import { Oi40DbResourceGroupRepositoryService } from './oi40DbResourceGroupRepository.service';
export * from './oi40DbSalesOrderLineRepository.service';
import { Oi40DbSalesOrderLineRepositoryService } from './oi40DbSalesOrderLineRepository.service';
export * from './oi40DbSalesOrderRepository.service';
import { Oi40DbSalesOrderRepositoryService } from './oi40DbSalesOrderRepository.service';
export * from './oi40DbScheduledWorkOrderRepository.service';
import { Oi40DbScheduledWorkOrderRepositoryService } from './oi40DbScheduledWorkOrderRepository.service';
export * from './oi40DbSecondaryResourceRepository.service';
import { Oi40DbSecondaryResourceRepositoryService } from './oi40DbSecondaryResourceRepository.service';
export * from './oi40DbSecondaryResourceUseSpecificationRepository.service';
import { Oi40DbSecondaryResourceUseSpecificationRepositoryService } from './oi40DbSecondaryResourceUseSpecificationRepository.service';
export * from './oi40DbStockSupplyRepository.service';
import { Oi40DbStockSupplyRepositoryService } from './oi40DbStockSupplyRepository.service';
export * from './oi40DbTaskProductionMaterialReservationRepository.service';
import { Oi40DbTaskProductionMaterialReservationRepositoryService } from './oi40DbTaskProductionMaterialReservationRepository.service';
export * from './oi40DbTaskPurchaseMaterialReservationRepository.service';
import { Oi40DbTaskPurchaseMaterialReservationRepositoryService } from './oi40DbTaskPurchaseMaterialReservationRepository.service';
export * from './oi40DbTaskRelationRepository.service';
import { Oi40DbTaskRelationRepositoryService } from './oi40DbTaskRelationRepository.service';
export * from './oi40DbTaskRepository.service';
import { Oi40DbTaskRepositoryService } from './oi40DbTaskRepository.service';
export * from './oi40DbTaskResourceReservationRepository.service';
import { Oi40DbTaskResourceReservationRepositoryService } from './oi40DbTaskResourceReservationRepository.service';
export * from './oi40DbTaskStockMaterialReservationRepository.service';
import { Oi40DbTaskStockMaterialReservationRepositoryService } from './oi40DbTaskStockMaterialReservationRepository.service';
export * from './oi40DbTimesheetMetaInfoExceptionRuleRepository.service';
import { Oi40DbTimesheetMetaInfoExceptionRuleRepositoryService } from './oi40DbTimesheetMetaInfoExceptionRuleRepository.service';
export * from './oi40DbTimesheetMetaInfoRepository.service';
import { Oi40DbTimesheetMetaInfoRepositoryService } from './oi40DbTimesheetMetaInfoRepository.service';
export * from './oi40DbTimesheetMetaInfoWorkingTimeRuleRepository.service';
import { Oi40DbTimesheetMetaInfoWorkingTimeRuleRepositoryService } from './oi40DbTimesheetMetaInfoWorkingTimeRuleRepository.service';
export * from './oi40DbWarehouseProductSettingRepository.service';
import { Oi40DbWarehouseProductSettingRepositoryService } from './oi40DbWarehouseProductSettingRepository.service';
export * from './oi40DbWarehouseRepository.service';
import { Oi40DbWarehouseRepositoryService } from './oi40DbWarehouseRepository.service';
export * from './oi40DbWorkCenterRepository.service';
import { Oi40DbWorkCenterRepositoryService } from './oi40DbWorkCenterRepository.service';
export * from './oi40DbWorkOrderRepository.service';
import { Oi40DbWorkOrderRepositoryService } from './oi40DbWorkOrderRepository.service';
export const APIS = [Oi40DbApsSchedulingSetRepositoryService, Oi40DbApsWindowRepositoryService, Oi40DbBomItemModelRepositoryService, Oi40DbChangeOverMatrixItemRepositoryService, Oi40DbCoProductItemRepositoryService, Oi40DbCycleModelRepositoryService, Oi40DbDepartmentRepositoryService, Oi40DbMachineEquipmentSpecificationRepositoryService, Oi40DbMachinePriorityRepositoryService, Oi40DbMachineRepositoryService, Oi40DbOperationEquipmentSpecificationRepositoryService, Oi40DbOperationModelRepositoryService, Oi40DbPartnerRepositoryService, Oi40DbPeggingRepositoryService, Oi40DbPlantProductSettingRepositoryService, Oi40DbPlantRepositoryService, Oi40DbProductRepositoryService, Oi40DbProductiveCompanyProductSettingRepositoryService, Oi40DbProductiveCompanyRepositoryService, Oi40DbPurchaseOrderLineRepositoryService, Oi40DbPurchaseOrderRepositoryService, Oi40DbResourceGroupRepositoryService, Oi40DbSalesOrderLineRepositoryService, Oi40DbSalesOrderRepositoryService, Oi40DbScheduledWorkOrderRepositoryService, Oi40DbSecondaryResourceRepositoryService, Oi40DbSecondaryResourceUseSpecificationRepositoryService, Oi40DbStockSupplyRepositoryService, Oi40DbTaskProductionMaterialReservationRepositoryService, Oi40DbTaskPurchaseMaterialReservationRepositoryService, Oi40DbTaskRelationRepositoryService, Oi40DbTaskRepositoryService, Oi40DbTaskResourceReservationRepositoryService, Oi40DbTaskStockMaterialReservationRepositoryService, Oi40DbTimesheetMetaInfoExceptionRuleRepositoryService, Oi40DbTimesheetMetaInfoRepositoryService, Oi40DbTimesheetMetaInfoWorkingTimeRuleRepositoryService, Oi40DbWarehouseProductSettingRepositoryService, Oi40DbWarehouseRepositoryService, Oi40DbWorkCenterRepositoryService, Oi40DbWorkOrderRepositoryService];
