/**
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OI40DBMachine { 
    attributesMap?: any;
    availability?: string;
    code?: string;
    description?: string;
    disabled?: boolean;
    infiniteCapacity?: boolean;
    integrationTs?: Date;
    modifiedTimestamp?: Date;
    removed?: boolean;
    timesheetMetaInfoCode?: string;
    workCenterCode?: string;
}
