/**
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OI40DBChangeOverMatrixItem } from './oI40DBChangeOverMatrixItem';
import { PageInfo } from './pageInfo';


export interface QbeSupportOI40DBChangeOverMatrixItem { 
    page?: PageInfo;
    qbe?: OI40DBChangeOverMatrixItem;
}
