/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBSalesOrderLine;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBSalesOrderLine;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBSalesOrderLine;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbSalesOrderLineRepositoryApi
 */
@Ignore
public class Oi40DbSalesOrderLineRepositoryApiTest {

    private final Oi40DbSalesOrderLineRepositoryApi api = new Oi40DbSalesOrderLineRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid22Test() {
        String code = null;
        api.deleteByCodeVoid22(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid22Test() {
        List<String> codes = null;
        api.deleteByCodesVoid22(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBSalesOrderLineTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBSalesOrderLine response = api.doAutocompletePageOI40DBSalesOrderLine(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBSalesOrderLineTest() {
        LookupData lookup = null;
        PageOI40DBSalesOrderLine response = api.doLookupPageOI40DBSalesOrderLine(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBSalesOrderLineTest() {
        List<OI40DBSalesOrderLine> response = api.findAllListOI40DBSalesOrderLine();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBSalesOrderLineTest() {
        PageInfo p = null;
        PageOI40DBSalesOrderLine response = api.findAllPageOI40DBSalesOrderLine(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBSalesOrderLineTest() {
        String ts = null;
        List<OI40DBSalesOrderLine> response = api.findByAfterIntegrationTsListOI40DBSalesOrderLine(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBSalesOrderLineTest() {
        String ts = null;
        List<OI40DBSalesOrderLine> response = api.findByAfterModifiedTimestampListOI40DBSalesOrderLine(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBSalesOrderLineTest() {
        String code = null;
        OI40DBSalesOrderLine response = api.findByCodeOI40DBSalesOrderLine(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBSalesOrderLineTest() {
        List<String> codes = null;
        List<OI40DBSalesOrderLine> response = api.findByCodesListOI40DBSalesOrderLine(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBSalesOrderLineTest() {
        OI40DBSalesOrderLine qbe = null;
        List<OI40DBSalesOrderLine> response = api.findByQbeListOI40DBSalesOrderLine(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBSalesOrderLineTest() {
        QbeSupportOI40DBSalesOrderLine qbe = null;
        PageOI40DBSalesOrderLine response = api.findByQbePagedPageOI40DBSalesOrderLine(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBSalesOrderLineTest() {
        List<OI40DBSalesOrderLine> data = null;
        List<OI40DBSalesOrderLine> response = api.updateListOI40DBSalesOrderLine(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBSalesOrderLineTest() {
        OI40DBSalesOrderLine data = null;
        OI40DBSalesOrderLine response = api.updateSingleOI40DBSalesOrderLine(data);

        // TODO: test validations
    }
    
}
