/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBScheduledWorkOrder;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBScheduledWorkOrder;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBScheduledWorkOrder;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbScheduledWorkOrderRepositoryApi
 */
@Ignore
public class Oi40DbScheduledWorkOrderRepositoryApiTest {

    private final Oi40DbScheduledWorkOrderRepositoryApi api = new Oi40DbScheduledWorkOrderRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid24Test() {
        String code = null;
        api.deleteByCodeVoid24(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid24Test() {
        List<String> codes = null;
        api.deleteByCodesVoid24(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBScheduledWorkOrderTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBScheduledWorkOrder response = api.doAutocompletePageOI40DBScheduledWorkOrder(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBScheduledWorkOrderTest() {
        LookupData lookup = null;
        PageOI40DBScheduledWorkOrder response = api.doLookupPageOI40DBScheduledWorkOrder(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBScheduledWorkOrderTest() {
        List<OI40DBScheduledWorkOrder> response = api.findAllListOI40DBScheduledWorkOrder();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBScheduledWorkOrderTest() {
        PageInfo p = null;
        PageOI40DBScheduledWorkOrder response = api.findAllPageOI40DBScheduledWorkOrder(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBScheduledWorkOrderTest() {
        String ts = null;
        List<OI40DBScheduledWorkOrder> response = api.findByAfterIntegrationTsListOI40DBScheduledWorkOrder(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBScheduledWorkOrderTest() {
        String ts = null;
        List<OI40DBScheduledWorkOrder> response = api.findByAfterModifiedTimestampListOI40DBScheduledWorkOrder(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBScheduledWorkOrderTest() {
        String code = null;
        OI40DBScheduledWorkOrder response = api.findByCodeOI40DBScheduledWorkOrder(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBScheduledWorkOrderTest() {
        List<String> codes = null;
        List<OI40DBScheduledWorkOrder> response = api.findByCodesListOI40DBScheduledWorkOrder(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBScheduledWorkOrderTest() {
        OI40DBScheduledWorkOrder qbe = null;
        List<OI40DBScheduledWorkOrder> response = api.findByQbeListOI40DBScheduledWorkOrder(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBScheduledWorkOrderTest() {
        QbeSupportOI40DBScheduledWorkOrder qbe = null;
        PageOI40DBScheduledWorkOrder response = api.findByQbePagedPageOI40DBScheduledWorkOrder(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBScheduledWorkOrderTest() {
        List<OI40DBScheduledWorkOrder> data = null;
        List<OI40DBScheduledWorkOrder> response = api.updateListOI40DBScheduledWorkOrder(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBScheduledWorkOrderTest() {
        OI40DBScheduledWorkOrder data = null;
        OI40DBScheduledWorkOrder response = api.updateSingleOI40DBScheduledWorkOrder(data);

        // TODO: test validations
    }
    
}
