/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBMachine;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBMachine;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBMachine;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbMachineRepositoryApi
 */
@Ignore
public class Oi40DbMachineRepositoryApiTest {

    private final Oi40DbMachineRepositoryApi api = new Oi40DbMachineRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid9Test() {
        String code = null;
        api.deleteByCodeVoid9(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid9Test() {
        List<String> codes = null;
        api.deleteByCodesVoid9(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBMachineTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBMachine response = api.doAutocompletePageOI40DBMachine(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBMachineTest() {
        LookupData lookup = null;
        PageOI40DBMachine response = api.doLookupPageOI40DBMachine(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBMachineTest() {
        List<OI40DBMachine> response = api.findAllListOI40DBMachine();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBMachineTest() {
        PageInfo p = null;
        PageOI40DBMachine response = api.findAllPageOI40DBMachine(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBMachineTest() {
        String ts = null;
        List<OI40DBMachine> response = api.findByAfterIntegrationTsListOI40DBMachine(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBMachineTest() {
        String ts = null;
        List<OI40DBMachine> response = api.findByAfterModifiedTimestampListOI40DBMachine(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBMachineTest() {
        String code = null;
        OI40DBMachine response = api.findByCodeOI40DBMachine(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBMachineTest() {
        List<String> codes = null;
        List<OI40DBMachine> response = api.findByCodesListOI40DBMachine(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBMachineTest() {
        OI40DBMachine qbe = null;
        List<OI40DBMachine> response = api.findByQbeListOI40DBMachine(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBMachineTest() {
        QbeSupportOI40DBMachine qbe = null;
        PageOI40DBMachine response = api.findByQbePagedPageOI40DBMachine(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBMachineTest() {
        List<OI40DBMachine> data = null;
        List<OI40DBMachine> response = api.updateListOI40DBMachine(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBMachineTest() {
        OI40DBMachine data = null;
        OI40DBMachine response = api.updateSingleOI40DBMachine(data);

        // TODO: test validations
    }
    
}
