/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBPlantProductSetting;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBPlantProductSetting;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBPlantProductSetting;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbPlantProductSettingRepositoryApi
 */
@Ignore
public class Oi40DbPlantProductSettingRepositoryApiTest {

    private final Oi40DbPlantProductSettingRepositoryApi api = new Oi40DbPlantProductSettingRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid14Test() {
        String code = null;
        api.deleteByCodeVoid14(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid14Test() {
        List<String> codes = null;
        api.deleteByCodesVoid14(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBPlantProductSettingTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBPlantProductSetting response = api.doAutocompletePageOI40DBPlantProductSetting(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBPlantProductSettingTest() {
        LookupData lookup = null;
        PageOI40DBPlantProductSetting response = api.doLookupPageOI40DBPlantProductSetting(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBPlantProductSettingTest() {
        List<OI40DBPlantProductSetting> response = api.findAllListOI40DBPlantProductSetting();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBPlantProductSettingTest() {
        PageInfo p = null;
        PageOI40DBPlantProductSetting response = api.findAllPageOI40DBPlantProductSetting(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBPlantProductSettingTest() {
        String ts = null;
        List<OI40DBPlantProductSetting> response = api.findByAfterIntegrationTsListOI40DBPlantProductSetting(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBPlantProductSettingTest() {
        String ts = null;
        List<OI40DBPlantProductSetting> response = api.findByAfterModifiedTimestampListOI40DBPlantProductSetting(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBPlantProductSettingTest() {
        String code = null;
        OI40DBPlantProductSetting response = api.findByCodeOI40DBPlantProductSetting(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBPlantProductSettingTest() {
        List<String> codes = null;
        List<OI40DBPlantProductSetting> response = api.findByCodesListOI40DBPlantProductSetting(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBPlantProductSettingTest() {
        OI40DBPlantProductSetting qbe = null;
        List<OI40DBPlantProductSetting> response = api.findByQbeListOI40DBPlantProductSetting(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBPlantProductSettingTest() {
        QbeSupportOI40DBPlantProductSetting qbe = null;
        PageOI40DBPlantProductSetting response = api.findByQbePagedPageOI40DBPlantProductSetting(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBPlantProductSettingTest() {
        List<OI40DBPlantProductSetting> data = null;
        List<OI40DBPlantProductSetting> response = api.updateListOI40DBPlantProductSetting(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBPlantProductSettingTest() {
        OI40DBPlantProductSetting data = null;
        OI40DBPlantProductSetting response = api.updateSingleOI40DBPlantProductSetting(data);

        // TODO: test validations
    }
    
}
