/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBSecondaryResourceUseSpecification;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBSecondaryResourceUseSpecification;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBSecondaryResourceUseSpecification;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbSecondaryResourceUseSpecificationRepositoryApi
 */
@Ignore
public class Oi40DbSecondaryResourceUseSpecificationRepositoryApiTest {

    private final Oi40DbSecondaryResourceUseSpecificationRepositoryApi api = new Oi40DbSecondaryResourceUseSpecificationRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid26Test() {
        String code = null;
        api.deleteByCodeVoid26(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid26Test() {
        List<String> codes = null;
        api.deleteByCodesVoid26(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBSecondaryResourceUseSpecificationTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBSecondaryResourceUseSpecification response = api.doAutocompletePageOI40DBSecondaryResourceUseSpecification(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBSecondaryResourceUseSpecificationTest() {
        LookupData lookup = null;
        PageOI40DBSecondaryResourceUseSpecification response = api.doLookupPageOI40DBSecondaryResourceUseSpecification(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBSecondaryResourceUseSpecificationTest() {
        List<OI40DBSecondaryResourceUseSpecification> response = api.findAllListOI40DBSecondaryResourceUseSpecification();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBSecondaryResourceUseSpecificationTest() {
        PageInfo p = null;
        PageOI40DBSecondaryResourceUseSpecification response = api.findAllPageOI40DBSecondaryResourceUseSpecification(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBSecondaryResourceUseSpecificationTest() {
        String ts = null;
        List<OI40DBSecondaryResourceUseSpecification> response = api.findByAfterIntegrationTsListOI40DBSecondaryResourceUseSpecification(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBSecondaryResourceUseSpecificationTest() {
        String ts = null;
        List<OI40DBSecondaryResourceUseSpecification> response = api.findByAfterModifiedTimestampListOI40DBSecondaryResourceUseSpecification(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBSecondaryResourceUseSpecificationTest() {
        String code = null;
        OI40DBSecondaryResourceUseSpecification response = api.findByCodeOI40DBSecondaryResourceUseSpecification(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBSecondaryResourceUseSpecificationTest() {
        List<String> codes = null;
        List<OI40DBSecondaryResourceUseSpecification> response = api.findByCodesListOI40DBSecondaryResourceUseSpecification(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBSecondaryResourceUseSpecificationTest() {
        OI40DBSecondaryResourceUseSpecification qbe = null;
        List<OI40DBSecondaryResourceUseSpecification> response = api.findByQbeListOI40DBSecondaryResourceUseSpecification(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBSecondaryResourceUseSpecificationTest() {
        QbeSupportOI40DBSecondaryResourceUseSpecification qbe = null;
        PageOI40DBSecondaryResourceUseSpecification response = api.findByQbePagedPageOI40DBSecondaryResourceUseSpecification(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBSecondaryResourceUseSpecificationTest() {
        List<OI40DBSecondaryResourceUseSpecification> data = null;
        List<OI40DBSecondaryResourceUseSpecification> response = api.updateListOI40DBSecondaryResourceUseSpecification(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBSecondaryResourceUseSpecificationTest() {
        OI40DBSecondaryResourceUseSpecification data = null;
        OI40DBSecondaryResourceUseSpecification response = api.updateSingleOI40DBSecondaryResourceUseSpecification(data);

        // TODO: test validations
    }
    
}
