/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBSalesOrder;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBSalesOrder;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBSalesOrder;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbSalesOrderRepositoryApi
 */
@Ignore
public class Oi40DbSalesOrderRepositoryApiTest {

    private final Oi40DbSalesOrderRepositoryApi api = new Oi40DbSalesOrderRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid23Test() {
        String code = null;
        api.deleteByCodeVoid23(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid23Test() {
        List<String> codes = null;
        api.deleteByCodesVoid23(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBSalesOrderTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBSalesOrder response = api.doAutocompletePageOI40DBSalesOrder(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBSalesOrderTest() {
        LookupData lookup = null;
        PageOI40DBSalesOrder response = api.doLookupPageOI40DBSalesOrder(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBSalesOrderTest() {
        List<OI40DBSalesOrder> response = api.findAllListOI40DBSalesOrder();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBSalesOrderTest() {
        PageInfo p = null;
        PageOI40DBSalesOrder response = api.findAllPageOI40DBSalesOrder(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBSalesOrderTest() {
        String ts = null;
        List<OI40DBSalesOrder> response = api.findByAfterIntegrationTsListOI40DBSalesOrder(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBSalesOrderTest() {
        String ts = null;
        List<OI40DBSalesOrder> response = api.findByAfterModifiedTimestampListOI40DBSalesOrder(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBSalesOrderTest() {
        String code = null;
        OI40DBSalesOrder response = api.findByCodeOI40DBSalesOrder(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBSalesOrderTest() {
        List<String> codes = null;
        List<OI40DBSalesOrder> response = api.findByCodesListOI40DBSalesOrder(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBSalesOrderTest() {
        OI40DBSalesOrder qbe = null;
        List<OI40DBSalesOrder> response = api.findByQbeListOI40DBSalesOrder(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBSalesOrderTest() {
        QbeSupportOI40DBSalesOrder qbe = null;
        PageOI40DBSalesOrder response = api.findByQbePagedPageOI40DBSalesOrder(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBSalesOrderTest() {
        List<OI40DBSalesOrder> data = null;
        List<OI40DBSalesOrder> response = api.updateListOI40DBSalesOrder(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBSalesOrderTest() {
        OI40DBSalesOrder data = null;
        OI40DBSalesOrder response = api.updateSingleOI40DBSalesOrder(data);

        // TODO: test validations
    }
    
}
