/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBWorkCenter;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBWorkCenter;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBWorkCenter;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbWorkCenterRepositoryApi
 */
@Ignore
public class Oi40DbWorkCenterRepositoryApiTest {

    private final Oi40DbWorkCenterRepositoryApi api = new Oi40DbWorkCenterRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid39Test() {
        String code = null;
        api.deleteByCodeVoid39(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid39Test() {
        List<String> codes = null;
        api.deleteByCodesVoid39(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBWorkCenterTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBWorkCenter response = api.doAutocompletePageOI40DBWorkCenter(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBWorkCenterTest() {
        LookupData lookup = null;
        PageOI40DBWorkCenter response = api.doLookupPageOI40DBWorkCenter(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBWorkCenterTest() {
        List<OI40DBWorkCenter> response = api.findAllListOI40DBWorkCenter();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBWorkCenterTest() {
        PageInfo p = null;
        PageOI40DBWorkCenter response = api.findAllPageOI40DBWorkCenter(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBWorkCenterTest() {
        String ts = null;
        List<OI40DBWorkCenter> response = api.findByAfterIntegrationTsListOI40DBWorkCenter(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBWorkCenterTest() {
        String ts = null;
        List<OI40DBWorkCenter> response = api.findByAfterModifiedTimestampListOI40DBWorkCenter(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBWorkCenterTest() {
        String code = null;
        OI40DBWorkCenter response = api.findByCodeOI40DBWorkCenter(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBWorkCenterTest() {
        List<String> codes = null;
        List<OI40DBWorkCenter> response = api.findByCodesListOI40DBWorkCenter(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBWorkCenterTest() {
        OI40DBWorkCenter qbe = null;
        List<OI40DBWorkCenter> response = api.findByQbeListOI40DBWorkCenter(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBWorkCenterTest() {
        QbeSupportOI40DBWorkCenter qbe = null;
        PageOI40DBWorkCenter response = api.findByQbePagedPageOI40DBWorkCenter(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBWorkCenterTest() {
        List<OI40DBWorkCenter> data = null;
        List<OI40DBWorkCenter> response = api.updateListOI40DBWorkCenter(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBWorkCenterTest() {
        OI40DBWorkCenter data = null;
        OI40DBWorkCenter response = api.updateSingleOI40DBWorkCenter(data);

        // TODO: test validations
    }
    
}
