/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBSecondaryResource;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBSecondaryResource;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBSecondaryResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbSecondaryResourceRepositoryApi
 */
@Ignore
public class Oi40DbSecondaryResourceRepositoryApiTest {

    private final Oi40DbSecondaryResourceRepositoryApi api = new Oi40DbSecondaryResourceRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid25Test() {
        String code = null;
        api.deleteByCodeVoid25(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid25Test() {
        List<String> codes = null;
        api.deleteByCodesVoid25(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBSecondaryResourceTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBSecondaryResource response = api.doAutocompletePageOI40DBSecondaryResource(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBSecondaryResourceTest() {
        LookupData lookup = null;
        PageOI40DBSecondaryResource response = api.doLookupPageOI40DBSecondaryResource(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBSecondaryResourceTest() {
        List<OI40DBSecondaryResource> response = api.findAllListOI40DBSecondaryResource();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBSecondaryResourceTest() {
        PageInfo p = null;
        PageOI40DBSecondaryResource response = api.findAllPageOI40DBSecondaryResource(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBSecondaryResourceTest() {
        String ts = null;
        List<OI40DBSecondaryResource> response = api.findByAfterIntegrationTsListOI40DBSecondaryResource(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBSecondaryResourceTest() {
        String ts = null;
        List<OI40DBSecondaryResource> response = api.findByAfterModifiedTimestampListOI40DBSecondaryResource(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBSecondaryResourceTest() {
        String code = null;
        OI40DBSecondaryResource response = api.findByCodeOI40DBSecondaryResource(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBSecondaryResourceTest() {
        List<String> codes = null;
        List<OI40DBSecondaryResource> response = api.findByCodesListOI40DBSecondaryResource(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBSecondaryResourceTest() {
        OI40DBSecondaryResource qbe = null;
        List<OI40DBSecondaryResource> response = api.findByQbeListOI40DBSecondaryResource(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBSecondaryResourceTest() {
        QbeSupportOI40DBSecondaryResource qbe = null;
        PageOI40DBSecondaryResource response = api.findByQbePagedPageOI40DBSecondaryResource(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBSecondaryResourceTest() {
        List<OI40DBSecondaryResource> data = null;
        List<OI40DBSecondaryResource> response = api.updateListOI40DBSecondaryResource(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBSecondaryResourceTest() {
        OI40DBSecondaryResource data = null;
        OI40DBSecondaryResource response = api.updateSingleOI40DBSecondaryResource(data);

        // TODO: test validations
    }
    
}
