/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBTimesheetMetaInfo;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBTimesheetMetaInfo;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBTimesheetMetaInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbTimesheetMetaInfoRepositoryApi
 */
@Ignore
public class Oi40DbTimesheetMetaInfoRepositoryApiTest {

    private final Oi40DbTimesheetMetaInfoRepositoryApi api = new Oi40DbTimesheetMetaInfoRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid35Test() {
        String code = null;
        api.deleteByCodeVoid35(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid35Test() {
        List<String> codes = null;
        api.deleteByCodesVoid35(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBTimesheetMetaInfoTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBTimesheetMetaInfo response = api.doAutocompletePageOI40DBTimesheetMetaInfo(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBTimesheetMetaInfoTest() {
        LookupData lookup = null;
        PageOI40DBTimesheetMetaInfo response = api.doLookupPageOI40DBTimesheetMetaInfo(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBTimesheetMetaInfoTest() {
        List<OI40DBTimesheetMetaInfo> response = api.findAllListOI40DBTimesheetMetaInfo();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBTimesheetMetaInfoTest() {
        PageInfo p = null;
        PageOI40DBTimesheetMetaInfo response = api.findAllPageOI40DBTimesheetMetaInfo(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBTimesheetMetaInfoTest() {
        String ts = null;
        List<OI40DBTimesheetMetaInfo> response = api.findByAfterIntegrationTsListOI40DBTimesheetMetaInfo(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBTimesheetMetaInfoTest() {
        String ts = null;
        List<OI40DBTimesheetMetaInfo> response = api.findByAfterModifiedTimestampListOI40DBTimesheetMetaInfo(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBTimesheetMetaInfoTest() {
        String code = null;
        OI40DBTimesheetMetaInfo response = api.findByCodeOI40DBTimesheetMetaInfo(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBTimesheetMetaInfoTest() {
        List<String> codes = null;
        List<OI40DBTimesheetMetaInfo> response = api.findByCodesListOI40DBTimesheetMetaInfo(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBTimesheetMetaInfoTest() {
        OI40DBTimesheetMetaInfo qbe = null;
        List<OI40DBTimesheetMetaInfo> response = api.findByQbeListOI40DBTimesheetMetaInfo(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBTimesheetMetaInfoTest() {
        QbeSupportOI40DBTimesheetMetaInfo qbe = null;
        PageOI40DBTimesheetMetaInfo response = api.findByQbePagedPageOI40DBTimesheetMetaInfo(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBTimesheetMetaInfoTest() {
        List<OI40DBTimesheetMetaInfo> data = null;
        List<OI40DBTimesheetMetaInfo> response = api.updateListOI40DBTimesheetMetaInfo(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBTimesheetMetaInfoTest() {
        OI40DBTimesheetMetaInfo data = null;
        OI40DBTimesheetMetaInfo response = api.updateSingleOI40DBTimesheetMetaInfo(data);

        // TODO: test validations
    }
    
}
