/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBCoProductItem;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBCoProductItem;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBCoProductItem;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbCoProductItemRepositoryApi
 */
@Ignore
public class Oi40DbCoProductItemRepositoryApiTest {

    private final Oi40DbCoProductItemRepositoryApi api = new Oi40DbCoProductItemRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid4Test() {
        String code = null;
        api.deleteByCodeVoid4(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid4Test() {
        List<String> codes = null;
        api.deleteByCodesVoid4(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBCoProductItemTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBCoProductItem response = api.doAutocompletePageOI40DBCoProductItem(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBCoProductItemTest() {
        LookupData lookup = null;
        PageOI40DBCoProductItem response = api.doLookupPageOI40DBCoProductItem(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBCoProductItemTest() {
        List<OI40DBCoProductItem> response = api.findAllListOI40DBCoProductItem();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBCoProductItemTest() {
        PageInfo p = null;
        PageOI40DBCoProductItem response = api.findAllPageOI40DBCoProductItem(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBCoProductItemTest() {
        String ts = null;
        List<OI40DBCoProductItem> response = api.findByAfterIntegrationTsListOI40DBCoProductItem(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBCoProductItemTest() {
        String ts = null;
        List<OI40DBCoProductItem> response = api.findByAfterModifiedTimestampListOI40DBCoProductItem(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBCoProductItemTest() {
        String code = null;
        OI40DBCoProductItem response = api.findByCodeOI40DBCoProductItem(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBCoProductItemTest() {
        List<String> codes = null;
        List<OI40DBCoProductItem> response = api.findByCodesListOI40DBCoProductItem(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBCoProductItemTest() {
        OI40DBCoProductItem qbe = null;
        List<OI40DBCoProductItem> response = api.findByQbeListOI40DBCoProductItem(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBCoProductItemTest() {
        QbeSupportOI40DBCoProductItem qbe = null;
        PageOI40DBCoProductItem response = api.findByQbePagedPageOI40DBCoProductItem(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBCoProductItemTest() {
        List<OI40DBCoProductItem> data = null;
        List<OI40DBCoProductItem> response = api.updateListOI40DBCoProductItem(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBCoProductItemTest() {
        OI40DBCoProductItem data = null;
        OI40DBCoProductItem response = api.updateSingleOI40DBCoProductItem(data);

        // TODO: test validations
    }
    
}
