/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBPartner;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBPartner;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBPartner;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbPartnerRepositoryApi
 */
@Ignore
public class Oi40DbPartnerRepositoryApiTest {

    private final Oi40DbPartnerRepositoryApi api = new Oi40DbPartnerRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid12Test() {
        String code = null;
        api.deleteByCodeVoid12(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid12Test() {
        List<String> codes = null;
        api.deleteByCodesVoid12(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBPartnerTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBPartner response = api.doAutocompletePageOI40DBPartner(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBPartnerTest() {
        LookupData lookup = null;
        PageOI40DBPartner response = api.doLookupPageOI40DBPartner(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBPartnerTest() {
        List<OI40DBPartner> response = api.findAllListOI40DBPartner();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBPartnerTest() {
        PageInfo p = null;
        PageOI40DBPartner response = api.findAllPageOI40DBPartner(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBPartnerTest() {
        String ts = null;
        List<OI40DBPartner> response = api.findByAfterIntegrationTsListOI40DBPartner(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBPartnerTest() {
        String ts = null;
        List<OI40DBPartner> response = api.findByAfterModifiedTimestampListOI40DBPartner(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBPartnerTest() {
        String code = null;
        OI40DBPartner response = api.findByCodeOI40DBPartner(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBPartnerTest() {
        List<String> codes = null;
        List<OI40DBPartner> response = api.findByCodesListOI40DBPartner(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBPartnerTest() {
        OI40DBPartner qbe = null;
        List<OI40DBPartner> response = api.findByQbeListOI40DBPartner(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBPartnerTest() {
        QbeSupportOI40DBPartner qbe = null;
        PageOI40DBPartner response = api.findByQbePagedPageOI40DBPartner(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBPartnerTest() {
        List<OI40DBPartner> data = null;
        List<OI40DBPartner> response = api.updateListOI40DBPartner(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBPartnerTest() {
        OI40DBPartner data = null;
        OI40DBPartner response = api.updateSingleOI40DBPartner(data);

        // TODO: test validations
    }
    
}
