/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBChangeOverMatrixItem;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBChangeOverMatrixItem;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBChangeOverMatrixItem;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbChangeOverMatrixItemRepositoryApi
 */
@Ignore
public class Oi40DbChangeOverMatrixItemRepositoryApiTest {

    private final Oi40DbChangeOverMatrixItemRepositoryApi api = new Oi40DbChangeOverMatrixItemRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid3Test() {
        String code = null;
        api.deleteByCodeVoid3(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid3Test() {
        List<String> codes = null;
        api.deleteByCodesVoid3(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBChangeOverMatrixItemTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBChangeOverMatrixItem response = api.doAutocompletePageOI40DBChangeOverMatrixItem(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBChangeOverMatrixItemTest() {
        LookupData lookup = null;
        PageOI40DBChangeOverMatrixItem response = api.doLookupPageOI40DBChangeOverMatrixItem(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBChangeOverMatrixItemTest() {
        List<OI40DBChangeOverMatrixItem> response = api.findAllListOI40DBChangeOverMatrixItem();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBChangeOverMatrixItemTest() {
        PageInfo p = null;
        PageOI40DBChangeOverMatrixItem response = api.findAllPageOI40DBChangeOverMatrixItem(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBChangeOverMatrixItemTest() {
        String ts = null;
        List<OI40DBChangeOverMatrixItem> response = api.findByAfterIntegrationTsListOI40DBChangeOverMatrixItem(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBChangeOverMatrixItemTest() {
        String ts = null;
        List<OI40DBChangeOverMatrixItem> response = api.findByAfterModifiedTimestampListOI40DBChangeOverMatrixItem(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBChangeOverMatrixItemTest() {
        String code = null;
        OI40DBChangeOverMatrixItem response = api.findByCodeOI40DBChangeOverMatrixItem(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBChangeOverMatrixItemTest() {
        List<String> codes = null;
        List<OI40DBChangeOverMatrixItem> response = api.findByCodesListOI40DBChangeOverMatrixItem(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBChangeOverMatrixItemTest() {
        OI40DBChangeOverMatrixItem qbe = null;
        List<OI40DBChangeOverMatrixItem> response = api.findByQbeListOI40DBChangeOverMatrixItem(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBChangeOverMatrixItemTest() {
        QbeSupportOI40DBChangeOverMatrixItem qbe = null;
        PageOI40DBChangeOverMatrixItem response = api.findByQbePagedPageOI40DBChangeOverMatrixItem(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBChangeOverMatrixItemTest() {
        List<OI40DBChangeOverMatrixItem> data = null;
        List<OI40DBChangeOverMatrixItem> response = api.updateListOI40DBChangeOverMatrixItem(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBChangeOverMatrixItemTest() {
        OI40DBChangeOverMatrixItem data = null;
        OI40DBChangeOverMatrixItem response = api.updateSingleOI40DBChangeOverMatrixItem(data);

        // TODO: test validations
    }
    
}
