/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.api;

import com.openi40.dbmodel.java.client.model.AutoCompleteData;
import com.openi40.dbmodel.java.client.model.LookupData;
import com.openi40.dbmodel.java.client.model.OI40DBWarehouseProductSetting;
import com.openi40.dbmodel.java.client.model.PageInfo;
import com.openi40.dbmodel.java.client.model.PageOI40DBWarehouseProductSetting;
import com.openi40.dbmodel.java.client.model.QbeSupportOI40DBWarehouseProductSetting;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oi40DbWarehouseProductSettingRepositoryApi
 */
@Ignore
public class Oi40DbWarehouseProductSettingRepositoryApiTest {

    private final Oi40DbWarehouseProductSettingRepositoryApi api = new Oi40DbWarehouseProductSettingRepositoryApi();

    
    /**
     * deleteByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodeVoid37Test() {
        String code = null;
        api.deleteByCodeVoid37(code);

        // TODO: test validations
    }
    
    /**
     * deleteByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteByCodesVoid37Test() {
        List<String> codes = null;
        api.deleteByCodesVoid37(codes);

        // TODO: test validations
    }
    
    /**
     * doAutocomplete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doAutocompletePageOI40DBWarehouseProductSettingTest() {
        AutoCompleteData autoCompleteData = null;
        PageOI40DBWarehouseProductSetting response = api.doAutocompletePageOI40DBWarehouseProductSetting(autoCompleteData);

        // TODO: test validations
    }
    
    /**
     * doLookup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void doLookupPageOI40DBWarehouseProductSettingTest() {
        LookupData lookup = null;
        PageOI40DBWarehouseProductSetting response = api.doLookupPageOI40DBWarehouseProductSetting(lookup);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllListOI40DBWarehouseProductSettingTest() {
        List<OI40DBWarehouseProductSetting> response = api.findAllListOI40DBWarehouseProductSetting();

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllPageOI40DBWarehouseProductSettingTest() {
        PageInfo p = null;
        PageOI40DBWarehouseProductSetting response = api.findAllPageOI40DBWarehouseProductSetting(p);

        // TODO: test validations
    }
    
    /**
     * findByAfterIntegrationTs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterIntegrationTsListOI40DBWarehouseProductSettingTest() {
        String ts = null;
        List<OI40DBWarehouseProductSetting> response = api.findByAfterIntegrationTsListOI40DBWarehouseProductSetting(ts);

        // TODO: test validations
    }
    
    /**
     * findByAfterModifiedTimestamp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByAfterModifiedTimestampListOI40DBWarehouseProductSettingTest() {
        String ts = null;
        List<OI40DBWarehouseProductSetting> response = api.findByAfterModifiedTimestampListOI40DBWarehouseProductSetting(ts);

        // TODO: test validations
    }
    
    /**
     * findByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodeOI40DBWarehouseProductSettingTest() {
        String code = null;
        OI40DBWarehouseProductSetting response = api.findByCodeOI40DBWarehouseProductSetting(code);

        // TODO: test validations
    }
    
    /**
     * findByCodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByCodesListOI40DBWarehouseProductSettingTest() {
        List<String> codes = null;
        List<OI40DBWarehouseProductSetting> response = api.findByCodesListOI40DBWarehouseProductSetting(codes);

        // TODO: test validations
    }
    
    /**
     * findByQbe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbeListOI40DBWarehouseProductSettingTest() {
        OI40DBWarehouseProductSetting qbe = null;
        List<OI40DBWarehouseProductSetting> response = api.findByQbeListOI40DBWarehouseProductSetting(qbe);

        // TODO: test validations
    }
    
    /**
     * findByQbePaged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByQbePagedPageOI40DBWarehouseProductSettingTest() {
        QbeSupportOI40DBWarehouseProductSetting qbe = null;
        PageOI40DBWarehouseProductSetting response = api.findByQbePagedPageOI40DBWarehouseProductSetting(qbe);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListOI40DBWarehouseProductSettingTest() {
        List<OI40DBWarehouseProductSetting> data = null;
        List<OI40DBWarehouseProductSetting> response = api.updateListOI40DBWarehouseProductSetting(data);

        // TODO: test validations
    }
    
    /**
     * updateSingle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSingleOI40DBWarehouseProductSettingTest() {
        OI40DBWarehouseProductSetting data = null;
        OI40DBWarehouseProductSetting response = api.updateSingleOI40DBWarehouseProductSetting(data);

        // TODO: test validations
    }
    
}
