hibernate.cache.use_second_level_cache: false        
#spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.hikari.connectionTimeout: 20000
spring.datasource.hikari.maximumPoolSize: 5
spring.datasource.username: postgres
spring.datasource.password: 15041973
spring.datasource.url:  jdbc:postgresql://192.168.23.135:5432/openi40mes

server:
  port: 8090
  servlet:
    contextPath: /openi40mes
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  
  
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      serialization:
          INDENT_OUTPUT: true

 
com.openi40.mes.logical.kernel.config:
                                  apsMsgRestConfig: 
                                      url: http://localhost:8080/openi40      

