/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * OI40DBStockSupply
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-29T17:41:29.716+01:00")
public class OI40DBStockSupply {
  @JsonProperty("attributesMap")
  private Object attributesMap = null;

  @JsonProperty("code")
  private String code = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("infiniteCapacity")
  private Boolean infiniteCapacity = null;

  @JsonProperty("integrationTs")
  private Date integrationTs = null;

  @JsonProperty("modifiedTimestamp")
  private Date modifiedTimestamp = null;

  @JsonProperty("physicalStockQuantity")
  private Double physicalStockQuantity = null;

  @JsonProperty("productCode")
  private String productCode = null;

  @JsonProperty("removed")
  private Boolean removed = null;

  @JsonProperty("warehouseCode")
  private String warehouseCode = null;

  public OI40DBStockSupply attributesMap(Object attributesMap) {
    this.attributesMap = attributesMap;
    return this;
  }

   /**
   * Get attributesMap
   * @return attributesMap
  **/
  @ApiModelProperty(value = "")
  public Object getAttributesMap() {
    return attributesMap;
  }

  public void setAttributesMap(Object attributesMap) {
    this.attributesMap = attributesMap;
  }

  public OI40DBStockSupply code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public OI40DBStockSupply description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OI40DBStockSupply infiniteCapacity(Boolean infiniteCapacity) {
    this.infiniteCapacity = infiniteCapacity;
    return this;
  }

   /**
   * Get infiniteCapacity
   * @return infiniteCapacity
  **/
  @ApiModelProperty(value = "")
  public Boolean isInfiniteCapacity() {
    return infiniteCapacity;
  }

  public void setInfiniteCapacity(Boolean infiniteCapacity) {
    this.infiniteCapacity = infiniteCapacity;
  }

  public OI40DBStockSupply integrationTs(Date integrationTs) {
    this.integrationTs = integrationTs;
    return this;
  }

   /**
   * Get integrationTs
   * @return integrationTs
  **/
  @ApiModelProperty(value = "")
  public Date getIntegrationTs() {
    return integrationTs;
  }

  public void setIntegrationTs(Date integrationTs) {
    this.integrationTs = integrationTs;
  }

  public OI40DBStockSupply modifiedTimestamp(Date modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
    return this;
  }

   /**
   * Get modifiedTimestamp
   * @return modifiedTimestamp
  **/
  @ApiModelProperty(value = "")
  public Date getModifiedTimestamp() {
    return modifiedTimestamp;
  }

  public void setModifiedTimestamp(Date modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
  }

  public OI40DBStockSupply physicalStockQuantity(Double physicalStockQuantity) {
    this.physicalStockQuantity = physicalStockQuantity;
    return this;
  }

   /**
   * Get physicalStockQuantity
   * @return physicalStockQuantity
  **/
  @ApiModelProperty(value = "")
  public Double getPhysicalStockQuantity() {
    return physicalStockQuantity;
  }

  public void setPhysicalStockQuantity(Double physicalStockQuantity) {
    this.physicalStockQuantity = physicalStockQuantity;
  }

  public OI40DBStockSupply productCode(String productCode) {
    this.productCode = productCode;
    return this;
  }

   /**
   * Get productCode
   * @return productCode
  **/
  @ApiModelProperty(value = "")
  public String getProductCode() {
    return productCode;
  }

  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }

  public OI40DBStockSupply removed(Boolean removed) {
    this.removed = removed;
    return this;
  }

   /**
   * Get removed
   * @return removed
  **/
  @ApiModelProperty(value = "")
  public Boolean isRemoved() {
    return removed;
  }

  public void setRemoved(Boolean removed) {
    this.removed = removed;
  }

  public OI40DBStockSupply warehouseCode(String warehouseCode) {
    this.warehouseCode = warehouseCode;
    return this;
  }

   /**
   * Get warehouseCode
   * @return warehouseCode
  **/
  @ApiModelProperty(value = "")
  public String getWarehouseCode() {
    return warehouseCode;
  }

  public void setWarehouseCode(String warehouseCode) {
    this.warehouseCode = warehouseCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OI40DBStockSupply oi40DBStockSupply = (OI40DBStockSupply) o;
    return Objects.equals(this.attributesMap, oi40DBStockSupply.attributesMap) &&
        Objects.equals(this.code, oi40DBStockSupply.code) &&
        Objects.equals(this.description, oi40DBStockSupply.description) &&
        Objects.equals(this.infiniteCapacity, oi40DBStockSupply.infiniteCapacity) &&
        Objects.equals(this.integrationTs, oi40DBStockSupply.integrationTs) &&
        Objects.equals(this.modifiedTimestamp, oi40DBStockSupply.modifiedTimestamp) &&
        Objects.equals(this.physicalStockQuantity, oi40DBStockSupply.physicalStockQuantity) &&
        Objects.equals(this.productCode, oi40DBStockSupply.productCode) &&
        Objects.equals(this.removed, oi40DBStockSupply.removed) &&
        Objects.equals(this.warehouseCode, oi40DBStockSupply.warehouseCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributesMap, code, description, infiniteCapacity, integrationTs, modifiedTimestamp, physicalStockQuantity, productCode, removed, warehouseCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OI40DBStockSupply {\n");
    
    sb.append("    attributesMap: ").append(toIndentedString(attributesMap)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    infiniteCapacity: ").append(toIndentedString(infiniteCapacity)).append("\n");
    sb.append("    integrationTs: ").append(toIndentedString(integrationTs)).append("\n");
    sb.append("    modifiedTimestamp: ").append(toIndentedString(modifiedTimestamp)).append("\n");
    sb.append("    physicalStockQuantity: ").append(toIndentedString(physicalStockQuantity)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("    warehouseCode: ").append(toIndentedString(warehouseCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

