/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * OI40DBSecondaryResourceUseSpecification
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-09T15:18:53.580+01:00")
public class OI40DBSecondaryResourceUseSpecification {
  @JsonProperty("afterStartMinutes")
  private Integer afterStartMinutes = null;

  @JsonProperty("attributesMap")
  private Object attributesMap = null;

  @JsonProperty("beforeStopMinutes")
  private Integer beforeStopMinutes = null;

  @JsonProperty("code")
  private String code = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("integrationTs")
  private Date integrationTs = null;

  @JsonProperty("maxQty")
  private Integer maxQty = null;

  @JsonProperty("minQty")
  private Integer minQty = null;

  @JsonProperty("modifiedTimestamp")
  private Date modifiedTimestamp = null;

  @JsonProperty("operationEquipmentSpecCode")
  private String operationEquipmentSpecCode = null;

  @JsonProperty("qty")
  private Integer qty = null;

  @JsonProperty("removed")
  private Boolean removed = null;

  @JsonProperty("secondaryResourceGroupCode")
  private String secondaryResourceGroupCode = null;

  @JsonProperty("useType")
  private String useType = null;

  @JsonProperty("usedTime")
  private String usedTime = null;

  public OI40DBSecondaryResourceUseSpecification afterStartMinutes(Integer afterStartMinutes) {
    this.afterStartMinutes = afterStartMinutes;
    return this;
  }

   /**
   * Get afterStartMinutes
   * @return afterStartMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getAfterStartMinutes() {
    return afterStartMinutes;
  }

  public void setAfterStartMinutes(Integer afterStartMinutes) {
    this.afterStartMinutes = afterStartMinutes;
  }

  public OI40DBSecondaryResourceUseSpecification attributesMap(Object attributesMap) {
    this.attributesMap = attributesMap;
    return this;
  }

   /**
   * Get attributesMap
   * @return attributesMap
  **/
  @ApiModelProperty(value = "")
  public Object getAttributesMap() {
    return attributesMap;
  }

  public void setAttributesMap(Object attributesMap) {
    this.attributesMap = attributesMap;
  }

  public OI40DBSecondaryResourceUseSpecification beforeStopMinutes(Integer beforeStopMinutes) {
    this.beforeStopMinutes = beforeStopMinutes;
    return this;
  }

   /**
   * Get beforeStopMinutes
   * @return beforeStopMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getBeforeStopMinutes() {
    return beforeStopMinutes;
  }

  public void setBeforeStopMinutes(Integer beforeStopMinutes) {
    this.beforeStopMinutes = beforeStopMinutes;
  }

  public OI40DBSecondaryResourceUseSpecification code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public OI40DBSecondaryResourceUseSpecification description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OI40DBSecondaryResourceUseSpecification integrationTs(Date integrationTs) {
    this.integrationTs = integrationTs;
    return this;
  }

   /**
   * Get integrationTs
   * @return integrationTs
  **/
  @ApiModelProperty(value = "")
  public Date getIntegrationTs() {
    return integrationTs;
  }

  public void setIntegrationTs(Date integrationTs) {
    this.integrationTs = integrationTs;
  }

  public OI40DBSecondaryResourceUseSpecification maxQty(Integer maxQty) {
    this.maxQty = maxQty;
    return this;
  }

   /**
   * Get maxQty
   * @return maxQty
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxQty() {
    return maxQty;
  }

  public void setMaxQty(Integer maxQty) {
    this.maxQty = maxQty;
  }

  public OI40DBSecondaryResourceUseSpecification minQty(Integer minQty) {
    this.minQty = minQty;
    return this;
  }

   /**
   * Get minQty
   * @return minQty
  **/
  @ApiModelProperty(value = "")
  public Integer getMinQty() {
    return minQty;
  }

  public void setMinQty(Integer minQty) {
    this.minQty = minQty;
  }

  public OI40DBSecondaryResourceUseSpecification modifiedTimestamp(Date modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
    return this;
  }

   /**
   * Get modifiedTimestamp
   * @return modifiedTimestamp
  **/
  @ApiModelProperty(value = "")
  public Date getModifiedTimestamp() {
    return modifiedTimestamp;
  }

  public void setModifiedTimestamp(Date modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
  }

  public OI40DBSecondaryResourceUseSpecification operationEquipmentSpecCode(String operationEquipmentSpecCode) {
    this.operationEquipmentSpecCode = operationEquipmentSpecCode;
    return this;
  }

   /**
   * Get operationEquipmentSpecCode
   * @return operationEquipmentSpecCode
  **/
  @ApiModelProperty(value = "")
  public String getOperationEquipmentSpecCode() {
    return operationEquipmentSpecCode;
  }

  public void setOperationEquipmentSpecCode(String operationEquipmentSpecCode) {
    this.operationEquipmentSpecCode = operationEquipmentSpecCode;
  }

  public OI40DBSecondaryResourceUseSpecification qty(Integer qty) {
    this.qty = qty;
    return this;
  }

   /**
   * Get qty
   * @return qty
  **/
  @ApiModelProperty(value = "")
  public Integer getQty() {
    return qty;
  }

  public void setQty(Integer qty) {
    this.qty = qty;
  }

  public OI40DBSecondaryResourceUseSpecification removed(Boolean removed) {
    this.removed = removed;
    return this;
  }

   /**
   * Get removed
   * @return removed
  **/
  @ApiModelProperty(value = "")
  public Boolean isRemoved() {
    return removed;
  }

  public void setRemoved(Boolean removed) {
    this.removed = removed;
  }

  public OI40DBSecondaryResourceUseSpecification secondaryResourceGroupCode(String secondaryResourceGroupCode) {
    this.secondaryResourceGroupCode = secondaryResourceGroupCode;
    return this;
  }

   /**
   * Get secondaryResourceGroupCode
   * @return secondaryResourceGroupCode
  **/
  @ApiModelProperty(value = "")
  public String getSecondaryResourceGroupCode() {
    return secondaryResourceGroupCode;
  }

  public void setSecondaryResourceGroupCode(String secondaryResourceGroupCode) {
    this.secondaryResourceGroupCode = secondaryResourceGroupCode;
  }

  public OI40DBSecondaryResourceUseSpecification useType(String useType) {
    this.useType = useType;
    return this;
  }

   /**
   * Get useType
   * @return useType
  **/
  @ApiModelProperty(value = "")
  public String getUseType() {
    return useType;
  }

  public void setUseType(String useType) {
    this.useType = useType;
  }

  public OI40DBSecondaryResourceUseSpecification usedTime(String usedTime) {
    this.usedTime = usedTime;
    return this;
  }

   /**
   * Get usedTime
   * @return usedTime
  **/
  @ApiModelProperty(value = "")
  public String getUsedTime() {
    return usedTime;
  }

  public void setUsedTime(String usedTime) {
    this.usedTime = usedTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OI40DBSecondaryResourceUseSpecification oi40DBSecondaryResourceUseSpecification = (OI40DBSecondaryResourceUseSpecification) o;
    return Objects.equals(this.afterStartMinutes, oi40DBSecondaryResourceUseSpecification.afterStartMinutes) &&
        Objects.equals(this.attributesMap, oi40DBSecondaryResourceUseSpecification.attributesMap) &&
        Objects.equals(this.beforeStopMinutes, oi40DBSecondaryResourceUseSpecification.beforeStopMinutes) &&
        Objects.equals(this.code, oi40DBSecondaryResourceUseSpecification.code) &&
        Objects.equals(this.description, oi40DBSecondaryResourceUseSpecification.description) &&
        Objects.equals(this.integrationTs, oi40DBSecondaryResourceUseSpecification.integrationTs) &&
        Objects.equals(this.maxQty, oi40DBSecondaryResourceUseSpecification.maxQty) &&
        Objects.equals(this.minQty, oi40DBSecondaryResourceUseSpecification.minQty) &&
        Objects.equals(this.modifiedTimestamp, oi40DBSecondaryResourceUseSpecification.modifiedTimestamp) &&
        Objects.equals(this.operationEquipmentSpecCode, oi40DBSecondaryResourceUseSpecification.operationEquipmentSpecCode) &&
        Objects.equals(this.qty, oi40DBSecondaryResourceUseSpecification.qty) &&
        Objects.equals(this.removed, oi40DBSecondaryResourceUseSpecification.removed) &&
        Objects.equals(this.secondaryResourceGroupCode, oi40DBSecondaryResourceUseSpecification.secondaryResourceGroupCode) &&
        Objects.equals(this.useType, oi40DBSecondaryResourceUseSpecification.useType) &&
        Objects.equals(this.usedTime, oi40DBSecondaryResourceUseSpecification.usedTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(afterStartMinutes, attributesMap, beforeStopMinutes, code, description, integrationTs, maxQty, minQty, modifiedTimestamp, operationEquipmentSpecCode, qty, removed, secondaryResourceGroupCode, useType, usedTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OI40DBSecondaryResourceUseSpecification {\n");
    
    sb.append("    afterStartMinutes: ").append(toIndentedString(afterStartMinutes)).append("\n");
    sb.append("    attributesMap: ").append(toIndentedString(attributesMap)).append("\n");
    sb.append("    beforeStopMinutes: ").append(toIndentedString(beforeStopMinutes)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    integrationTs: ").append(toIndentedString(integrationTs)).append("\n");
    sb.append("    maxQty: ").append(toIndentedString(maxQty)).append("\n");
    sb.append("    minQty: ").append(toIndentedString(minQty)).append("\n");
    sb.append("    modifiedTimestamp: ").append(toIndentedString(modifiedTimestamp)).append("\n");
    sb.append("    operationEquipmentSpecCode: ").append(toIndentedString(operationEquipmentSpecCode)).append("\n");
    sb.append("    qty: ").append(toIndentedString(qty)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("    secondaryResourceGroupCode: ").append(toIndentedString(secondaryResourceGroupCode)).append("\n");
    sb.append("    useType: ").append(toIndentedString(useType)).append("\n");
    sb.append("    usedTime: ").append(toIndentedString(usedTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

