/*
 * Openi40
 * The open source industy 4.0 production scheduler & MES platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openi40.dbmodel.java.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * OI40DBTaskProductionMaterialReservation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-09T15:18:53.580+01:00")
public class OI40DBTaskProductionMaterialReservation {
  @JsonProperty("attributesMap")
  private Object attributesMap = null;

  @JsonProperty("batchQty")
  private Double batchQty = null;

  @JsonProperty("code")
  private String code = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("endTransfer")
  private Date endTransfer = null;

  @JsonProperty("integrationTs")
  private Date integrationTs = null;

  @JsonProperty("machineCode")
  private String machineCode = null;

  @JsonProperty("modifiedTimestamp")
  private Date modifiedTimestamp = null;

  @JsonProperty("nrTransfers")
  private Double nrTransfers = null;

  @JsonProperty("productCode")
  private String productCode = null;

  @JsonProperty("qtyReserved")
  private Double qtyReserved = null;

  @JsonProperty("removed")
  private Boolean removed = null;

  @JsonProperty("startTransfer")
  private Date startTransfer = null;

  @JsonProperty("supplyTaskCode")
  private String supplyTaskCode = null;

  @JsonProperty("supplyWorkOrderCode")
  private String supplyWorkOrderCode = null;

  @JsonProperty("taskCode")
  private String taskCode = null;

  @JsonProperty("transferType")
  private String transferType = null;

  @JsonProperty("warehouseCode")
  private String warehouseCode = null;

  @JsonProperty("workCenterCode")
  private String workCenterCode = null;

  public OI40DBTaskProductionMaterialReservation attributesMap(Object attributesMap) {
    this.attributesMap = attributesMap;
    return this;
  }

   /**
   * Get attributesMap
   * @return attributesMap
  **/
  @ApiModelProperty(value = "")
  public Object getAttributesMap() {
    return attributesMap;
  }

  public void setAttributesMap(Object attributesMap) {
    this.attributesMap = attributesMap;
  }

  public OI40DBTaskProductionMaterialReservation batchQty(Double batchQty) {
    this.batchQty = batchQty;
    return this;
  }

   /**
   * Get batchQty
   * @return batchQty
  **/
  @ApiModelProperty(value = "")
  public Double getBatchQty() {
    return batchQty;
  }

  public void setBatchQty(Double batchQty) {
    this.batchQty = batchQty;
  }

  public OI40DBTaskProductionMaterialReservation code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public OI40DBTaskProductionMaterialReservation description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OI40DBTaskProductionMaterialReservation endTransfer(Date endTransfer) {
    this.endTransfer = endTransfer;
    return this;
  }

   /**
   * Get endTransfer
   * @return endTransfer
  **/
  @ApiModelProperty(value = "")
  public Date getEndTransfer() {
    return endTransfer;
  }

  public void setEndTransfer(Date endTransfer) {
    this.endTransfer = endTransfer;
  }

  public OI40DBTaskProductionMaterialReservation integrationTs(Date integrationTs) {
    this.integrationTs = integrationTs;
    return this;
  }

   /**
   * Get integrationTs
   * @return integrationTs
  **/
  @ApiModelProperty(value = "")
  public Date getIntegrationTs() {
    return integrationTs;
  }

  public void setIntegrationTs(Date integrationTs) {
    this.integrationTs = integrationTs;
  }

  public OI40DBTaskProductionMaterialReservation machineCode(String machineCode) {
    this.machineCode = machineCode;
    return this;
  }

   /**
   * Get machineCode
   * @return machineCode
  **/
  @ApiModelProperty(value = "")
  public String getMachineCode() {
    return machineCode;
  }

  public void setMachineCode(String machineCode) {
    this.machineCode = machineCode;
  }

  public OI40DBTaskProductionMaterialReservation modifiedTimestamp(Date modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
    return this;
  }

   /**
   * Get modifiedTimestamp
   * @return modifiedTimestamp
  **/
  @ApiModelProperty(value = "")
  public Date getModifiedTimestamp() {
    return modifiedTimestamp;
  }

  public void setModifiedTimestamp(Date modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
  }

  public OI40DBTaskProductionMaterialReservation nrTransfers(Double nrTransfers) {
    this.nrTransfers = nrTransfers;
    return this;
  }

   /**
   * Get nrTransfers
   * @return nrTransfers
  **/
  @ApiModelProperty(value = "")
  public Double getNrTransfers() {
    return nrTransfers;
  }

  public void setNrTransfers(Double nrTransfers) {
    this.nrTransfers = nrTransfers;
  }

  public OI40DBTaskProductionMaterialReservation productCode(String productCode) {
    this.productCode = productCode;
    return this;
  }

   /**
   * Get productCode
   * @return productCode
  **/
  @ApiModelProperty(value = "")
  public String getProductCode() {
    return productCode;
  }

  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }

  public OI40DBTaskProductionMaterialReservation qtyReserved(Double qtyReserved) {
    this.qtyReserved = qtyReserved;
    return this;
  }

   /**
   * Get qtyReserved
   * @return qtyReserved
  **/
  @ApiModelProperty(value = "")
  public Double getQtyReserved() {
    return qtyReserved;
  }

  public void setQtyReserved(Double qtyReserved) {
    this.qtyReserved = qtyReserved;
  }

  public OI40DBTaskProductionMaterialReservation removed(Boolean removed) {
    this.removed = removed;
    return this;
  }

   /**
   * Get removed
   * @return removed
  **/
  @ApiModelProperty(value = "")
  public Boolean isRemoved() {
    return removed;
  }

  public void setRemoved(Boolean removed) {
    this.removed = removed;
  }

  public OI40DBTaskProductionMaterialReservation startTransfer(Date startTransfer) {
    this.startTransfer = startTransfer;
    return this;
  }

   /**
   * Get startTransfer
   * @return startTransfer
  **/
  @ApiModelProperty(value = "")
  public Date getStartTransfer() {
    return startTransfer;
  }

  public void setStartTransfer(Date startTransfer) {
    this.startTransfer = startTransfer;
  }

  public OI40DBTaskProductionMaterialReservation supplyTaskCode(String supplyTaskCode) {
    this.supplyTaskCode = supplyTaskCode;
    return this;
  }

   /**
   * Get supplyTaskCode
   * @return supplyTaskCode
  **/
  @ApiModelProperty(value = "")
  public String getSupplyTaskCode() {
    return supplyTaskCode;
  }

  public void setSupplyTaskCode(String supplyTaskCode) {
    this.supplyTaskCode = supplyTaskCode;
  }

  public OI40DBTaskProductionMaterialReservation supplyWorkOrderCode(String supplyWorkOrderCode) {
    this.supplyWorkOrderCode = supplyWorkOrderCode;
    return this;
  }

   /**
   * Get supplyWorkOrderCode
   * @return supplyWorkOrderCode
  **/
  @ApiModelProperty(value = "")
  public String getSupplyWorkOrderCode() {
    return supplyWorkOrderCode;
  }

  public void setSupplyWorkOrderCode(String supplyWorkOrderCode) {
    this.supplyWorkOrderCode = supplyWorkOrderCode;
  }

  public OI40DBTaskProductionMaterialReservation taskCode(String taskCode) {
    this.taskCode = taskCode;
    return this;
  }

   /**
   * Get taskCode
   * @return taskCode
  **/
  @ApiModelProperty(value = "")
  public String getTaskCode() {
    return taskCode;
  }

  public void setTaskCode(String taskCode) {
    this.taskCode = taskCode;
  }

  public OI40DBTaskProductionMaterialReservation transferType(String transferType) {
    this.transferType = transferType;
    return this;
  }

   /**
   * Get transferType
   * @return transferType
  **/
  @ApiModelProperty(value = "")
  public String getTransferType() {
    return transferType;
  }

  public void setTransferType(String transferType) {
    this.transferType = transferType;
  }

  public OI40DBTaskProductionMaterialReservation warehouseCode(String warehouseCode) {
    this.warehouseCode = warehouseCode;
    return this;
  }

   /**
   * Get warehouseCode
   * @return warehouseCode
  **/
  @ApiModelProperty(value = "")
  public String getWarehouseCode() {
    return warehouseCode;
  }

  public void setWarehouseCode(String warehouseCode) {
    this.warehouseCode = warehouseCode;
  }

  public OI40DBTaskProductionMaterialReservation workCenterCode(String workCenterCode) {
    this.workCenterCode = workCenterCode;
    return this;
  }

   /**
   * Get workCenterCode
   * @return workCenterCode
  **/
  @ApiModelProperty(value = "")
  public String getWorkCenterCode() {
    return workCenterCode;
  }

  public void setWorkCenterCode(String workCenterCode) {
    this.workCenterCode = workCenterCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OI40DBTaskProductionMaterialReservation oi40DBTaskProductionMaterialReservation = (OI40DBTaskProductionMaterialReservation) o;
    return Objects.equals(this.attributesMap, oi40DBTaskProductionMaterialReservation.attributesMap) &&
        Objects.equals(this.batchQty, oi40DBTaskProductionMaterialReservation.batchQty) &&
        Objects.equals(this.code, oi40DBTaskProductionMaterialReservation.code) &&
        Objects.equals(this.description, oi40DBTaskProductionMaterialReservation.description) &&
        Objects.equals(this.endTransfer, oi40DBTaskProductionMaterialReservation.endTransfer) &&
        Objects.equals(this.integrationTs, oi40DBTaskProductionMaterialReservation.integrationTs) &&
        Objects.equals(this.machineCode, oi40DBTaskProductionMaterialReservation.machineCode) &&
        Objects.equals(this.modifiedTimestamp, oi40DBTaskProductionMaterialReservation.modifiedTimestamp) &&
        Objects.equals(this.nrTransfers, oi40DBTaskProductionMaterialReservation.nrTransfers) &&
        Objects.equals(this.productCode, oi40DBTaskProductionMaterialReservation.productCode) &&
        Objects.equals(this.qtyReserved, oi40DBTaskProductionMaterialReservation.qtyReserved) &&
        Objects.equals(this.removed, oi40DBTaskProductionMaterialReservation.removed) &&
        Objects.equals(this.startTransfer, oi40DBTaskProductionMaterialReservation.startTransfer) &&
        Objects.equals(this.supplyTaskCode, oi40DBTaskProductionMaterialReservation.supplyTaskCode) &&
        Objects.equals(this.supplyWorkOrderCode, oi40DBTaskProductionMaterialReservation.supplyWorkOrderCode) &&
        Objects.equals(this.taskCode, oi40DBTaskProductionMaterialReservation.taskCode) &&
        Objects.equals(this.transferType, oi40DBTaskProductionMaterialReservation.transferType) &&
        Objects.equals(this.warehouseCode, oi40DBTaskProductionMaterialReservation.warehouseCode) &&
        Objects.equals(this.workCenterCode, oi40DBTaskProductionMaterialReservation.workCenterCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributesMap, batchQty, code, description, endTransfer, integrationTs, machineCode, modifiedTimestamp, nrTransfers, productCode, qtyReserved, removed, startTransfer, supplyTaskCode, supplyWorkOrderCode, taskCode, transferType, warehouseCode, workCenterCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OI40DBTaskProductionMaterialReservation {\n");
    
    sb.append("    attributesMap: ").append(toIndentedString(attributesMap)).append("\n");
    sb.append("    batchQty: ").append(toIndentedString(batchQty)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    endTransfer: ").append(toIndentedString(endTransfer)).append("\n");
    sb.append("    integrationTs: ").append(toIndentedString(integrationTs)).append("\n");
    sb.append("    machineCode: ").append(toIndentedString(machineCode)).append("\n");
    sb.append("    modifiedTimestamp: ").append(toIndentedString(modifiedTimestamp)).append("\n");
    sb.append("    nrTransfers: ").append(toIndentedString(nrTransfers)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("    qtyReserved: ").append(toIndentedString(qtyReserved)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("    startTransfer: ").append(toIndentedString(startTransfer)).append("\n");
    sb.append("    supplyTaskCode: ").append(toIndentedString(supplyTaskCode)).append("\n");
    sb.append("    supplyWorkOrderCode: ").append(toIndentedString(supplyWorkOrderCode)).append("\n");
    sb.append("    taskCode: ").append(toIndentedString(taskCode)).append("\n");
    sb.append("    transferType: ").append(toIndentedString(transferType)).append("\n");
    sb.append("    warehouseCode: ").append(toIndentedString(warehouseCode)).append("\n");
    sb.append("    workCenterCode: ").append(toIndentedString(workCenterCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

