DROP TABLE aps_window;
DROP table tsheet_meta;
DROP TABLE prdive_company;
DROP TABLE plant;
DROP TABLE dept;
DROP TABLE work_center;
DROP TABLE mac;
DROP TABLE chng_over_matrix_item;
DROP TABLE resource_group;
DROP TABLE rc;
DROP TABLE whouse;
DROP TABLE prd;
DROP TABLE stock_supply;
DROP TABLE cycle_model;
DROP TABLE sales_order;
DROP TABLE purch_order;
DROP TABLE prdive_company_prd_setting;
DROP TABLE plant_prd_setting;
DROP TABLE whouse_prd_setting;
DROP TABLE sales_order_line;
DROP TABLE purch_order_line;
DROP TABLE work_order;
DROP TABLE task;
DROP TABLE task_relation;
DROP TABLE tsheet_meta_exc_rule;
DROP TABLE tsheet_meta_working_time_rule;
DROP TABLE op_model;
DROP TABLE bom_item_model;
DROP TABLE co_prd_item;
DROP TABLE cons_batching_info;
DROP TABLE op_equip_spec;
DROP TABLE mac_equip_spec;
DROP TABLE producing_batching_info;
DROP TABLE bom_item_batch_info;
DROP TABLE mac_priority;
DROP TABLE rc_use_spec;
DROP table rc_group_reserv ;
DROP table whouse_picklist ;
DROP table task_picklist;
DROP table purchase_picklist ;
DROP table pegging;
DROP table scheduling_set ;
DROP table scheduled_wo;
DROP TABLE partner;
DROP TABLE OI40_INCREMENTAL_SYNC;
DROP TABLE OI40_DELETED_ENTRIES ;
DROP TABLE acq_setup_resources ;
DROP TABLE acq_work_resources ;
DROP TABLE msg_spooler_entry;
DROP TABLE msg_spooler_proc;
